services:
  rover:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        L4T_VERSION_MAJOR: 36 # jetpack version 36.4.0 
        L4T_VERSION_MINOR: 4
        L4T_VERSION_PATCH: 0
        ZED_SDK_MAJOR: 5 # ZED SDK version 5.0.3
        ZED_SDK_MINOR: 0
        ZED_SDK_PATCH: 3
        ZED_ROS2_WRAPPER_FOLDER: /home/zed_ros2_ws
        ZED_ROS2_WRAPPER_BRANCH: master
        ZED_ROS2_WRAPPER_URL: https://github.com/stereolabs/zed-ros2-wrapper.git
    container_name: rover-software
    volumes:
      - ../src:/workspace/src
      - /lib/modules/5.15.148-tegra:/lib/modules/5.15.148-tegra
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      # - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    network_mode: host
    privileged: true
    runtime: nvidia
    devices:
      - /dev:/dev
    # restart: unless-stopped
