services:
  rover:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        L4T_VERSION_MAJOR: 36 # jetpack version 36.4.0 
        L4T_VERSION_MINOR: 4
        L4T_VERSION_PATCH: 0
        ZED_SDK_MAJOR: 5 # ZED SDK version 5.0.3
        ZED_SDK_MINOR: 0
        ZED_SDK_PATCH: 3
        ROS2_WRAPPER_FOLDER: /home/ros2_ws
        ZED_ROS2_WRAPPER_BRANCH: master
        ZED_ROS2_WRAPPER_URL: https://github.com/stereolabs/zed-ros2-wrapper.git
    container_name: rover-software
    volumes:
      - ../src:/home/workspace/src
      - /tmp/argus_socket:/tmp/argus_socket
      - /lib/modules/5.15.148-tegra:/lib/modules/5.15.148-tegra
      - /dev/:/dev/
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev/shm:/dev/shm
    working_dir: /home/workspace
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    privileged: true
    runtime: nvidia
    devices:
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3

  cameras:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
      args:
        L4T_VERSION_MAJOR: 36 # jetpack version 36.4.0 
        L4T_VERSION_MINOR: 4
        L4T_VERSION_PATCH: 0
        ZED_SDK_MAJOR: 5 # ZED SDK version 5.0.3
        ZED_SDK_MINOR: 0
        ZED_SDK_PATCH: 3
        ROS2_WRAPPER_FOLDER: /home/ros2_ws
        ZED_ROS2_WRAPPER_BRANCH: master
        ZED_ROS2_WRAPPER_URL: https://github.com/stereolabs/zed-ros2-wrapper.git
    container_name: rover-cameras
    volumes:
      - ../src:/home/workspace/src
      - /tmp/argus_socket:/tmp/argus_socket
      - /lib/modules/5.15.148-tegra:/lib/modules/5.15.148-tegra
      - /dev/:/dev/
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev/shm:/dev/shm
    working_dir: /home/workspace
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    privileged: true
    runtime: nvidia
    restart: unless-stopped
    devices:
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
    entrypoint: ["/bin/bash"]
    command: ["-c", "source /opt/ros/humble/setup.bash && source /home/workspace/install/setup.bash && ros2 launch gorm_sensors cameras.launch.py"]

  rover-deploy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
      args:
        L4T_VERSION_MAJOR: 36 # jetpack version 36.4.0 
        L4T_VERSION_MINOR: 4
        L4T_VERSION_PATCH: 0
        ZED_SDK_MAJOR: 5 # ZED SDK version 5.0.3
        ZED_SDK_MINOR: 0
        ZED_SDK_PATCH: 3
        ROS2_WRAPPER_FOLDER: /home/ros2_ws
        ZED_ROS2_WRAPPER_BRANCH: master
        ZED_ROS2_WRAPPER_URL: https://github.com/stereolabs/zed-ros2-wrapper.git
    container_name: rover-software-deploy
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /lib/modules/5.15.148-tegra:/lib/modules/5.15.148-tegra
      - /dev/:/dev/
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings:/usr/local/zed/settings
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /dev/shm:/dev/shm
    working_dir: /home/workspace
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    privileged: true
    runtime: nvidia
    restart: unless-stopped
    devices:
      - /dev:/dev
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
    command: ["autostart"]

  triton-server:
    image: nvcr.io/nvidia/tritonserver:23.02-py3
    container_name: triton-server
    volumes:
      - ./triton_models:/models
    network_mode: host
    # ports:
    #   - "8000:8000" # HTTP
    #   - "8001:8001" # gRPC
    #   - "8002:8002" # Metrics
    command: tritonserver --model-repository=/models
    runtime: nvidia
    privileged: true
