twist_mux:
  ros__parameters:
    cmd_vel_out: "cmd_vel_out"
    topics:
      joystick:
        topic: "joystick/cmd_vel"
        timeout: 0.5
        priority: 100
      remote:
        topic: "remote/cmd_vel"
        timeout: 0.5
        priority: 90
      autonomous:
        topic: "autonomous/cmd_vel"
        timeout: 0.5
        priority: 10
