[book]
authors = ["abmoRobotics"]
language = "en"
multilingual = false
src = "src"
title = "AAU Rover Software Documentation"
[preprocessor.katex]
inline-delimiter = ["$", "$"]

[output.html]
mathjax-support = true
